USE [master]
GO

/****** Object:  Database [PRJ301Assignment]    Script Date: 6/22/2022 11:46:57 PM ******/
CREATE DATABASE [PRJ301Assignment]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRJ301Assignment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRJ301Assignment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRJ301Assignment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRJ301Assignment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRJ301Assignment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRJ301Assignment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET RECOVERY FULL 
GO

ALTER DATABASE [PRJ301Assignment] SET  MULTI_USER 
GO

ALTER DATABASE [PRJ301Assignment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRJ301Assignment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRJ301Assignment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRJ301Assignment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRJ301Assignment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRJ301Assignment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRJ301Assignment] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRJ301Assignment] SET  READ_WRITE 
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Course]    Script Date: 6/22/2022 11:48:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[SAccount]    Script Date: 6/22/2022 11:49:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Student]    Script Date: 6/22/2022 11:50:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Student](
	[studentID] [varchar](50) NOT NULL,
	[studentName] [nvarchar](50) NOT NULL,
	[groupID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[studentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[SAccount]    Script Date: 6/22/2022 11:54:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAccount](
	[username] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[studentID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_SAccount] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAccount]  WITH CHECK ADD  CONSTRAINT [FK_SAccount_Student] FOREIGN KEY([password])
REFERENCES [dbo].[Student] ([studentID])
GO

ALTER TABLE [dbo].[SAccount] CHECK CONSTRAINT [FK_SAccount_Student]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Course]    Script Date: 6/22/2022 11:55:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Course](
	[courseID] [varchar](50) NOT NULL,
	[courseName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[courseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Groups]    Script Date: 6/22/2022 11:55:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Groups](
	[groupID] [varchar](50) NOT NULL,
	[courseID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
(
	[groupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Groups]  WITH CHECK ADD  CONSTRAINT [FK_Groups_Course] FOREIGN KEY([courseID])
REFERENCES [dbo].[Course] ([courseID])
GO

ALTER TABLE [dbo].[Groups] CHECK CONSTRAINT [FK_Groups_Course]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Student_group]    Script Date: 6/22/2022 11:55:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Student_group](
	[groupID] [varchar](50) NOT NULL,
	[studentID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_group_list] PRIMARY KEY CLUSTERED 
(
	[groupID] ASC,
	[studentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Student_group]  WITH CHECK ADD  CONSTRAINT [FK_group_list_Groups] FOREIGN KEY([groupID])
REFERENCES [dbo].[Groups] ([groupID])
GO

ALTER TABLE [dbo].[Student_group] CHECK CONSTRAINT [FK_group_list_Groups]
GO

ALTER TABLE [dbo].[Student_group]  WITH CHECK ADD  CONSTRAINT [FK_Student_group_Student] FOREIGN KEY([studentID])
REFERENCES [dbo].[Student] ([studentID])
GO

ALTER TABLE [dbo].[Student_group] CHECK CONSTRAINT [FK_Student_group_Student]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Instructor]    Script Date: 6/22/2022 11:56:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Instructor](
	[instructorID] [varchar](50) NOT NULL,
	[instructorName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[instructorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[IAccount]    Script Date: 6/22/2022 11:56:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IAccount](
	[username] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[intructorID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[IAccount]  WITH CHECK ADD  CONSTRAINT [FK_EAccount_Employee] FOREIGN KEY([intructorID])
REFERENCES [dbo].[Instructor] ([instructorID])
GO

ALTER TABLE [dbo].[IAccount] CHECK CONSTRAINT [FK_EAccount_Employee]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[TimeSlot]    Script Date: 6/22/2022 11:56:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TimeSlot](
	[slot] [int] NOT NULL,
	[start] [time](7) NOT NULL,
	[finish] [time](7) NOT NULL,
 CONSTRAINT [PK_TimeSlot] PRIMARY KEY CLUSTERED 
(
	[slot] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Room]    Script Date: 6/22/2022 11:56:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Room](
	[roomID] [varchar](50) NOT NULL,
	[building] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED 
(
	[roomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [PRJ301Assignment]
GO

/****** Object:  Table [dbo].[Lession]    Script Date: 6/22/2022 11:57:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Lession](
	[lessionID] [int] NOT NULL,
	[groupID] [varchar](50) NOT NULL,
	[lecture] [varchar](50) NOT NULL,
	[instructorID] [varchar](50) NOT NULL,
	[slot] [int] NOT NULL,
	[roomID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Lession] PRIMARY KEY CLUSTERED 
(
	[lessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Lession]  WITH CHECK ADD  CONSTRAINT [FK_Lession_Groups] FOREIGN KEY([groupID])
REFERENCES [dbo].[Groups] ([groupID])
GO

ALTER TABLE [dbo].[Lession] CHECK CONSTRAINT [FK_Lession_Groups]
GO

ALTER TABLE [dbo].[Lession]  WITH CHECK ADD  CONSTRAINT [FK_Lession_Instructor] FOREIGN KEY([instructorID])
REFERENCES [dbo].[Instructor] ([instructorID])
GO

ALTER TABLE [dbo].[Lession] CHECK CONSTRAINT [FK_Lession_Instructor]
GO

ALTER TABLE [dbo].[Lession]  WITH CHECK ADD  CONSTRAINT [FK_Lession_Room] FOREIGN KEY([roomID])
REFERENCES [dbo].[Room] ([roomID])
GO

ALTER TABLE [dbo].[Lession] CHECK CONSTRAINT [FK_Lession_Room]
GO

ALTER TABLE [dbo].[Lession]  WITH CHECK ADD  CONSTRAINT [FK_Lession_TimeSlot] FOREIGN KEY([slot])
REFERENCES [dbo].[TimeSlot] ([slot])
GO

ALTER TABLE [dbo].[Lession] CHECK CONSTRAINT [FK_Lession_TimeSlot]
GO







